### ISSUE TITLE
Glue in JS based TeX/LaTeX projects

### ISSUE THREAD

**Issue by sirinath** [michael-brade/LaTeX.js#103]
I stumbled across  [Boxes and Glue: A Brief, but Visual, Introduction Using LuaTeX](https://www.overleaf.com/learn/latex/Articles/Boxes_and_Glue:_A_Brief,_but_Visual,_Introduction_Using_LuaTeX) which demonstrates glues in the browser using [LuaTeX: Parsing typeset paragraphs](https://www.overleaf.com/latex/examples/using-a-luatex-callback-to-parse-typeset-paragraphs/mzbpwxtjshsj). I believe this uses [Overleaf](https://www.overleaf.com/) or/and [ShareLaTeX](https://www.sharelatex.com/) componenet.

Maybe you can do something similar.

**Comment by michael-brade** [comment]
Thank you for the comment! You are right, this uses Overleaf, and that means they render the LaTeX code on the server natively and then display the resulting PDF using pdf.js, they don't use plain HTML and CSS. So no, sadly, I cannot use that...

**Comment by sirinath** [comment]
If `pdf.js` renders it then perhaps the same technique used in `pdf.js` can be used.  But having said that `LaTeX.js` is impressive as it is.

**Comment by michael-brade** [comment]
No, not if you want HTML. `pdf.js` renders to HTML `<canvas>`, so it is an image and doesn't really have anything to do with HTML and CSS or JavaScript anymore.

**Comment by sirinath** [comment]
Ah, OK.

**Comment by sirinath** [comment]
Following projects might be of interest which is looking for print perfect webpages with polyfills: https://www.pagedjs.org/, https://www.cabbagetreelabs.org/, https://editoria.pub/. https://coko.foundation/,

**Comment by michael-brade** [comment]
Oh wow, thank you very much! I like that a lot. Maybe I can somehow use paged.js...

**Comment by sirinath** [comment]
I am not sure if the features you require are in it but perhaps you can suggest. These will become standard in the browser.
