### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by NishealJ** [michael-brade/LaTeX.js#115]
/usr/local/lib/node_modules/latex.js/dist/latex.js:1
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):(t=t||self).latexjs=e()}(this,function(){"use strict";var commonjsGlobal="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{};function unwrapExports(t){return t&&t.__esModule&&Object.prototype.hasOwnProperty.call(t,"default")?t.default:t}function createCommonjsModule(t,e){return t(e={exports:{}},e.exports),e.exports}var he=createCommonjsModule(function(t,e){!function(r){var n=e,i=t&&t.exports==n&&t,a="object"==typeof commonjsGlobal&&commonjsGlobal;a.global!==a&&a.window!==a||(r=a);var o=/[\uD800-\uDBFF][\uDC00-\uDFFF]/g,s=/[\x01-\x7F]/g,l=/[\x01-\t\x0B\f\x0E-\x1F\x7F\x81\x8D\x8F\x90\x9D\xA0-\uFFFF]/g,u=/<\u20D2|=\u20E5|>\u20D2|\u205F\u200A|\u219D\u0338|\u2202\u0338|\u2220\u20D2|\u2229\uFE00|\u222A\uFE00|\u223C\u20D2|\u223D\u0331|\u223

TypeError: Cannot read property 'createElement' of undefined
    at e (/usr/local/lib/node_modules/latex.js/dist/latex.js:1:550171)
    at /usr/local/lib/node_modules/latex.js/dist/latex.js:1:550503
    at /usr/local/lib/node_modules/latex.js/dist/latex.js:1:558181
    at createCommonjsModule (/usr/local/lib/node_modules/latex.js/dist/latex.js:1:506)
    at /usr/local/lib/node_modules/latex.js/dist/latex.js:1:548662
    at /usr/local/lib/node_modules/latex.js/dist/latex.js:1:84
    at Object.<anonymous> (/usr/local/lib/node_modules/latex.js/dist/latex.js:1:160)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by NishealJ** [comment]
Hi @michael-brade, I get this error while using the command latex-js

**Comment by michael-brade** [comment]
Hi, which version of LaTeX.js are you using, how did you install it and how did you start this? 

BTW, I'll do a new release in the next hour, that *should* fix those bugs.

**Comment by michael-brade** [comment]
No response anymore, so closing this. If you still have this or a similar problem with the current release, please reopen.
