### ISSUE TITLE
Size compared to MathJax?

### ISSUE THREAD

**Issue by mspanish** [michael-brade/LaTeX.js#117]
This looks great. I'm looking for something smaller than MathJax, as I already have another lightweight script that converts entries to LaTeX - but I can't seem to figure out how many KB this would add to my es6 project, whereas MathJax adds 600+KB minified.

lovely work.

**Comment by michael-brade** [comment]
Thank you :-) 

The pure javascript is about 550kB minified, and this includes KaTeX. However, I don't know what exactly you mean by "add to project", so if you want to be able to render the result, you will need the fonts as well, and those are almost 8MB.
