### ISSUE TITLE
LaTeX.js Completely in Browser

### ISSUE THREAD

**Issue by joel1robertson** [michael-brade/LaTeX.js#14]
Hello, I would like to use LaTeX.js in a browser (as opposed to from the command line) to accept a LaTeX string and return an HTML string without having to make a call to the server to perform the translation. Is this possible? My end goal is to then feed the HTML string into CKEditor, allow the user to edit it, and then manually translate the HTML back into LaTeX. My page does not have a server back-end.

**Comment by joel1robertson** [comment]
Great! That's what I originally thought, but when I looked at the "usage" in your README.md and only saw instructions for CLI, I got concerned.

I have looked at the playground and was not sure where to start. Doing something like
`<script>var latexjs = require('latexjs')</script>`
gives me
`ReferenceError: Can't find variable: require`

Sorry, I need a little direction. Your playground is a great example, but way too sophisticated for me to grasp all at once.

**Comment by michael-brade** [comment]
I see--lack of documentation, as always...

Yes, you cannot use that code directly in the browser, you need to transform it using webpack and babel. The browser doesn't know about `require` or modules. 

And then you really only need [this](https://github.com/michael-brade/LaTeX.js/blob/f2339cf73f5aee4d708a0e0d494428c8bb7f855d/docs/js/playground.js#L39) line (`latex` being the variable holding the LaTeX source to translate), everything else is error handling and optimization. And, of course, line 7 to create the `HtmlGenerator`.

**Comment by williamstein** [comment]
It might be nice to make a precompiled version and put it on a CDN...

**Comment by michael-brade** [comment]
Very true! I was already wondering how to put it into the next release. I guess I'll just call it `latex.js` and put the parser and generator into it.

**Comment by joel1robertson** [comment]
Thanks for all your help. I'll see if this gets me going.

**Comment by au-re** [comment]
I'm trying to access the `HtmlGenerator`.
I'm importing `latex.js` in this way:
```js
import latexjs from "latex.js";
console.log(latexjs.HtmlGenerator); // undefined
```
I also tried
```js
import HtmlGenerator from "latex.js/html-generator.js"; // cannot resolve
```
What's the recommended approach? Would it be possible to make it available as a named export besides the parser?
```js
import latexjs, { HtmlGenerator } from "latex.js";
```

**Comment by michael-brade** [comment]
@au-re Yes, I'm working on exactly that. Give me one or two more weeks - my time is rather limited at the moment.

However, for now you can get it to work by adding `dist` to the path:

```
import HtmlGenerator from "latex.js/dist/html-generator.js";
```

**Comment by michael-brade** [comment]
Alright, done! I have exported the API, updated the documentation in the README, added library and browser usage examples and put a precompiled `latex.min.js` on a CDN (well, jsDelivr gives it to us from NPM for free). You will need at least version 0.10.1.

**Comment by joel1robertson** [comment]
Awesome! Thanks! I’m on vacation the next three business days—I’ll check it out when I get back.

**Comment by michael-brade** [comment]
I guess this one is done. Please reopen if any issues remain.

**Comment by joel1robertson** [comment]
Thanks! I was able to get it going, but ended up having to go in a somewhat different direction due to needing to retain context. Since I was using this to subsequently edit the document with an HTML editor, the great H&J work you did to make the LaTeX look correct kept me from being able to tell the difference between things like a line wrap, a line break, or a paragraph break.

Joel Robertson
317-443-5516

**Comment by michael-brade** [comment]
Oh... I'm not sure I completely understand. Doesn't the HTML structure tell you exactly those differences? Or did you mean you couldn't tell *visually*? Then some CSS could have solved it. In either case, I'd be interested to hear which direction you chose to solve it.

PS: I have no idea what H&J stands for :innocent:

**Comment by joel1robertson** [comment]
I couldn’t tell within the HTML.

H&J is hyphenation and justification. It’s an old typesetting term.

Joel Robertson
317-443-5516

**Comment by michael-brade** [comment]
Hehe, I see. I guess in the context of typesetting I must have understood it naturally, though I probably never really noticed it, but thinking about LaTeX.js I only had "HTML&JavaScript" in mind :smile: 

But... it should be possible to tell:

* `</p>` means paragraph break
* `<br>` means line break
* `<span class="breakspace">` means line break with explicit extra vertical space (e.g. `\\[2em]`)
* and everything else is a line wrap done by the browser. That is, if you can see the result. If you want to tell by just looking at the HTML, you won't find the line wraps.
