### ISSUE TITLE
Convert Latext to PDF

### ISSUE THREAD

**Issue by arhariri79** [michael-brade/LaTeX.js#141]
Hello
Thank you for latex.js 
I want to convert latex js to pdf without any third party library . 
Please help me. 

Thanks a lot my dear.

**Comment by michael-brade** [comment]
Hi, thank you. But for PDF output, LaTeX is actually the right tool. LaTeX.js is meant to output HTML, it will _never_ support PDF. 

cheers, Michael

**Comment by arhariri79** [comment]
Hi 
thank your for your response , 
but i have admin panel that user upload latex file and then i convert to html with latex.js in client and i want convert pdf like the html . 
that mean i want convert latex file to pdf in client . 
thanks my dear .

**Comment by michael-brade** [comment]
I see. Then you have to use your browser's ability to turn a webpage (html) to PDF by exporting the page as PDF or printing it. But that is a very inferior way of doing it. The browser's quality is nowhere near the original LaTeX output quality... you could maybe use a webservice that creates the PDF on the server with a standard TeXLive installation and then send the PDF back to the client. I would think that there already are such services or implementations.
