### ISSUE TITLE
newline rule

### ISSUE THREAD

**Issue by johnwebner** [michael-brade/LaTeX.js#21]
Shouldn't '\r' be after '\r\n'? Like [here](https://github.com/pegjs/pegjs/blob/4964b9af7e33a1c804eaff21d337d0d0926f9717/src/parser.pegjs#L251-L256)

https://github.com/michael-brade/LaTeX.js/blob/a5b822ba25af9aae8d15564bf2cbf1b05dbbb9aa/src/latex-parser.pegjs#L827

**Comment by michael-brade** [comment]
Yes, it should! Thanks for finding this :grin: I guess it's time for another unit test.

**Comment by michael-brade** [comment]
oh, guess I was too fast (and too smart back then when I wrote it :stuck_out_tongue_winking_eye: ). The not `!` is the key to make this work. But I agree, it's much more readable without the not, so I'll change it.

**Comment by johnwebner** [comment]
I have tried the following in PEG.js online and I got `r` output for `rn` input. 
`nl = 
!'r''n'.* {return "n"}
/ 'r' .* {return "r"}
/ 'rn' .* {return "rn" }`


The rule will never make it to `'rn' .* {return "rn" }`

**Comment by michael-brade** [comment]
Ok, thinking about it again, you are right. First rule will be ignored if it finds an `r`, and then the second one will immediately eat the `r`, so the next time the first will match, never the last one. At least that was the logic I had in mind first this morning.

Now, what I don't really understand yet is that why LaTeX.js, when actually I tried to verify it, didn't interpret `\r\n` as a paragraph break?! I need to do some debugging...

**Comment by michael-brade** [comment]
This is really interesting. Even with the new (and correct) code, LaTeX.js/PEG.js never matches the `\r\n` char sequence. Only `\r` or `\n`, and if it is `\r`, the `\n` that follows it seems to be eaten by something else. This may be a bug in PEG.js. I don't know yet. So my question to you, since you seem to be using Windows: is it possible for you to use this rule
```
nl "newline"  = "\n"  { console.log("n") } / "\r\n" { console.log("rn") } / "\r" { console.log("r") }
```
and run it on a file with Windows EOLs and two or three lines, and then send me the console output?

**Comment by johnwebner** [comment]
This rule seems to be correct and that's how I have done it.
I have used notepad++ to create the following lines:
![latexjs](https://user-images.githubusercontent.com/38671577/45913607-fc493380-be35-11e8-998a-8e5a38f9e41e.png)
and this is the output: 
`rn
n
n
rn
r
rn
n
n
r`

**Comment by michael-brade** [comment]
Oh my my.... /me == not so smart after all. The (second) bug is in load-fixtures.ls, which splits the lines to find the tests, and then joins them again with `\n`. Thank you, I'll have to fix that, too :smile:
