### ISSUE TITLE
Could latex.js support latex template?

### ISSUE THREAD

**Issue by seuliang** [michael-brade/LaTeX.js#61]
Could latex.js support latex template?
Could it be done?

**Comment by michael-brade** [comment]
Hm, could you be a bit more specific? I don't know what "latex template" is....

**Comment by seuliang** [comment]
Many academic journals provide LaTeX templates for authors to submit articles (also known as publications or papers) for review. These templates typically mimic the layout of the articles published by the journal and allow the author to preview their written work in this final layout.

**Comment by michael-brade** [comment]
Oh, I see. Well, in that case, there is nothing to be done in LaTeX.js, for LaTeX.js is the program that translates documents, including those templates. How or where you store those templates will not be dictated by LaTeX.js.
