### ISSUE TITLE
what‘s typse of arguments in function create: (type, children, classes = "") 

### ISSUE THREAD

**Issue by seuliang** [michael-brade/LaTeX.js#77]
see： https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/html-generator.ls#L359  

I want to know the types of 'type','children'. they are Node or Element or Htmlelement ?

**Comment by michael-brade** [comment]
* `type`: `string` or `Element`
* `children`: an `Element` or an array of `Element`

I'll put that in the code as a comment :-)

**Comment by seuliang** [comment]
Thank you.
