### ISSUE TITLE
where the declaration of  _title  in  base.ls

### ISSUE THREAD

**Issue by seuliang** [michael-brade/LaTeX.js#78]
at:
https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/documentclasses/base.ls#L182

@_title  @_author @_date  @_thanks  come from html-generator.ts ?

**Comment by michael-brade** [comment]
No, not really. grep for `_author`, for instance, and you'll find:
https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/latex.ltx.ls#L223

`latex.ltx.ls` imports the macros of the documentclass, so the documentclass has access to all macros in `latex.ltx`--just like in the real LaTeX :-) Then you have to use `\author{yadda}` to set `_author`.

**Comment by seuliang** [comment]
could they be separate ?  
latex.ltx.ls  require base.ls, I think it's better that base.ls is independent from latex.ltx.ls.

**Comment by michael-brade** [comment]
no, I don't think so. `latex.ltx.ls` doesn't require `base.ls`. Where did you find that?

**Comment by seuliang** [comment]
https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/latex.ltx.ls#L1189
not base.ls  directly, but article.ls and several other ls file which extend from base.ls.

**Comment by michael-brade** [comment]
I see. Yes, but that is not a real dependency, just so that the build system knows what to include in the browser bundle. How would you change that?

**Comment by seuliang** [comment]
I'm not familiar with this part. I don't know hao to implement this in typescript.

**Comment by michael-brade** [comment]
Ah, so you are writing typescript definitions for LaTeX.js? Or are you completely reimplementing it?

**Comment by seuliang** [comment]
i'm reimplementing it with typescript.
typescript is more easier for beginner.

**Comment by michael-brade** [comment]
cool. I'm looking forward to the code :-)

**Comment by seuliang** [comment]
in typescript. i think a Latex object should be passed to Base to access functions in Latex.

**Comment by michael-brade** [comment]
I don't know what you mean. What is a "Latex object"? Can you give me a code example what you want to do?

**Comment by seuliang** [comment]
in src/documentclasses/base.ts
````
import { LaTeX } from "../latex.ltx"
export class Base{
    constructor(generator:HtmlGenerator, latex:LaTeX, options:string[]){}
}
    this.latex['title'] = this.latex['author'] = this.latex['date'] = this.latex['thanks'] = this.latex['and'] = this['maketitle'] = function(){};

````

**Comment by michael-brade** [comment]
Ok. But then you have to find a way to add macros that are defined in a documentclass to `LaTeX`. Or somehow make it possible for a Generator to call the macros of a documentclass. How would you do that?

The reason I wrote the code this way is: Base/Documentclass doesn't call LaTeX, it just adds macros to LaTeX, and then the Generator calls LaTeX (macros). If you change Base, you will have to change all that. Same with packages: they just add macros to LaTeX.

**Comment by seuliang** [comment]
I have figured out how to import functions to class `LaTeX` in typescript, but haven't found method to import module dynamically with `rollup`.
