### ISSUE TITLE
what's difference between @\maketitle and \maketitle

### ISSUE THREAD

**Issue by seuliang** [michael-brade/LaTeX.js#80]
https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/documentclasses/base.ls#L187

and 
https://github.com/michael-brade/LaTeX.js/blob/245ca82d22c9f9d4dc34041833316667b2f17af6/src/documentclasses/base.ls#L160

Are they different?

**Comment by michael-brade** [comment]
absolutely. `@` is a shortcut for `this`. Line 160 is the method definition, line 187 just deletes all those methods so that `\maketitle` can only be called once.
