### ISSUE TITLE
not working in Microsoft Edge

### ISSUE THREAD

**Issue by derzaarsad** [michael-brade/LaTeX.js#83]
it works in Mozilla Firefox but not in Microsoft edge. Maybe there is a subtle difference between the two?

**Comment by michael-brade** [comment]
Haha :-D *subtle*... no, it's Microsoft, it's a huge difference! LaTeX.js will probably never work in IE, but it could/should work in Edge. I don't have Edge, so I don't know why exactly it doesn't work. Any details?

**Comment by derzaarsad** [comment]
Just insrall dual boot :)) I'll see if I can extract a debug/error message.

**Comment by derzaarsad** [comment]
<img width="997" alt="error_message" src="https://user-images.githubusercontent.com/10983251/61583548-d7971880-ab39-11e9-9459-5416985387a9.PNG">
as promise. Here is the error message

**Comment by michael-brade** [comment]
Darn... the first one is the interesting one (why doesn't Edge support source maps?). But it means Edge isn't able to process `{ ...o }`. I tried to get rollup to output ES3 but there seems to be not option to do that. So for now, I don't know how to fix this.

**Comment by michael-brade** [comment]
closing this, as it only affects the playground, and only if used with Edge (global usage about 1%), so it's not worth the effort IMHO.
