### ISSUE TITLE
Tree-sitter parser

### ISSUE THREAD

**Issue by kskyten** [michael-brade/LaTeX.js#90]
Implementing the parser with [tree-sitter](https://github.com/tree-sitter/tree-sitter) would give a syntax tree (see #10), editor support and bindings to many other languages for free. It also has [WebAssembly bindings](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web) for web use. I haven't tried it myself, but it seems that the parser grammar is defined in javascript.

**Comment by michael-brade** [comment]
Nice, I think tree-sitter is an amazing tool! But I also think that it is the wrong tool for this project (at this point in time) because it would mean I would have to drop PEG.js and completely rewrite the whole grammar. If possible, I'd rather add the AST to PEG.js.
