### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by yangdaweihit** [michael-brade/LaTeX.js#95]
When I try to run `latex.js test.tex -o test.html`, errors arise as follows:

```
error loading package "ctex": Error: Cannot find module './packages/ctex.js'
error loading package "booktabs": Error: Cannot find module './packages/booktabs.js'
error loading package "amsmath": Error: Cannot find module './packages/amsmath.js'
error loading package "geometry": Error: Cannot find module './packages/geometry.js'
error loading package "subcaption": Error: Cannot find module './packages/subcaption.js'
SyntaxError: unknown environment: equation
```

`tes.tex` see https://paste.ubuntu.com/p/wsrCWJQt6g/

Please show me the correct way to use `latex.js`. Thanks in advance.

**Comment by michael-brade** [comment]
Hi, this is easy to answer: the reason is that I am slow... ;-) Your document is using almost only unimplemented features: tables, figures, and the missing packages above. I will implement those things eventually.
