### ISSUE TITLE
code-of-merit.org

### ISSUE THREAD

**Issue by Aspie96** [michael-brade/LaTeX.js#98]
The link is broken.

**Comment by Aspie96** [comment]
To address the issue, I created the following repository:
https://github.com/Aspie96/Code-of-Merit

I will be thinking about how to recreate the website while still following the license of the code.

**Comment by michael-brade** [comment]
Thank you! This is great, I would then link to the new website. I didn't know Roberto left (or was forced to [again] by github). Either way, it's shocking to see the direction that many things are going.

**Comment by Aspie96** [comment]
I think we should defenitely investigate that (without releasing any information without his consent, of course, if we obtain it from him).

I agree we are moving in the wrong direction (and I am left-leaning). Please, let's stick together and move in the right direction.

(Note: I am not the only fork of the repo and there are unmodified ones. I do intend to modify the repo, in order to update it, so that it's not a "dead repository", document what happened, adapt the website etc...).

**Comment by michael-brade** [comment]
Lovely! You have my support. It looks like Roberto is really active on gitlab, so I am confident he will answer. Let me know if you want my help.

**Comment by Aspie96** [comment]
I haven't written him yet, nor do I think I will this night (it's 1:3 in Italy), but I defenitely will tomorrow (I will keep lurking online for a while, though, so I will probably answer. I know, unhealthy to go to sleep late XD).

Thank you for your support, I really do appreciate.

**Comment by Aspie96** [comment]
Isn't it amazing how we can be nice to each other without a "proper" code of conduct? (It's almost like it's not needed).

**Comment by michael-brade** [comment]
LOL :-))) Absolutely! I had a really long and beautiful exchange about the code of conduct with someone from the Netherlands and there I also said pretty much the same thing :) However, apparently it wasn't appreciated and the whole discussion was deleted. You could still find it in google's cache, but it's gone there now as well. I still have it on my hard drive, in case you are interested.

**Comment by michael-brade** [comment]
Oh yeah, I do have that bad habit of working too long, too... 1:17am, I'm off to bed now :-)

**Comment by Aspie96** [comment]
Whenever something ever so slightly controversial happens, one should archive it on the Wayback Machine (Archive.org is one of the best non-profits on the web to be honest) or similar websites.
Archive.is can also get it from the cache of Google or other services.

**Comment by michael-brade** [comment]
I didn't know that you could manually make them archive anything? Well, if that's the case, that's really good to know!

**Comment by Aspie96** [comment]
> I didn't know that you could manually make them archive anything?

You can.

Go here:
> https://archive.org/web/

And "Save page now". If you create an account it gives you the option to bookmark it for you.

**Comment by Aspie96** [comment]
Hi, sorry for being late.

You can find the website at:
https://codeofmerit.org/

**Comment by michael-brade** [comment]
Thanks a lot! Well done, I like it and have updated the link.

**Comment by Aspie96** [comment]
Thank you, but I have a suggestion.
The attribution is:
> This document is adapted from the Code of Merit (https://codeofmerit.org), version 1.0.

The problem is that it may suggest that the URL is that of the "original" Code of Merit, which it isn't.
Instead, I suggest this:

> This document is adapted from the Code of Merit, version 1.0. See: https://codeofmerit.org/.

The wording is nearly identical, but, in my view, writing "See: ..." instead implies there is more information about the attribution.

And indeed, the "License" section contains all the required information, except for the old URL, which isn't required, since it no longer qualifies as a link to the material.

**Comment by michael-brade** [comment]
To be honest, I don't think it makes a difference at all, both versions rely on interpretation by the user. I'd say it is natural to expect more information on a referenced website, with or without "see", "see also", etc. Plus, I stated that this version is not the original, so again, it is natural to check the website for the original.

**Comment by Aspie96** [comment]
I agree, it was a very pedantic complaint.
Thank you again and good luck for your project!

Il giorno sab 11 gen 2020 alle ore 09:26 Michael Brade <
notifications@github.com> ha scritto:
